function execute() {
    return Response.success([
        {title: "Action", input: "https://ln.hako.vn/the-loai/action", script: "gen.js"},
        {title: "Adapted to Anime", input: "https://ln.hako.vn/the-loai/adapted-to-anime", script: "gen.js"},
        {title: "Adapted to Drama CD", input: "https://ln.hako.vn/the-loai/adapted-to-drama-cd", script: "gen.js"},
        {title: "Adapted to Manga", input: "https://ln.hako.vn/the-loai/adapted-to-manga", script: "gen.js"},
        {title: "Adult", input: "https://ln.hako.vn/the-loai/adult", script: "gen.js"},
        {title: "Adventure", input: "https://ln.hako.vn/the-loai/adventure", script: "gen.js"},
        {title: "Chinese Novel", input: "https://ln.hako.vn/the-loai/chinese-novel", script: "gen.js"},
        {title: "Comedy", input: "https://ln.hako.vn/the-loai/comedy", script: "gen.js"},
        {title: "Cooking", input: "https://ln.hako.vn/the-loai/cooking", script: "gen.js"},
        {title: "Drama", input: "https://ln.hako.vn/the-loai/drama", script: "gen.js"},
        {title: "Ecchi", input: "https://ln.hako.vn/the-loai/ecchi", script: "gen.js"},
        {title: "English Novel", input: "https://ln.hako.vn/the-loai/english-novel", script: "gen.js"},
        {title: "Fantasy", input: "https://ln.hako.vn/the-loai/fantasy", script: "gen.js"},
        {title: "Game", input: "https://ln.hako.vn/the-loai/game", script: "gen.js"},
        {title: "Gender Bender", input: "https://ln.hako.vn/the-loai/gender-bender", script: "gen.js"},
        {title: "Harem", input: "https://ln.hako.vn/the-loai/harem", script: "gen.js"},
        {title: "Historical", input: "https://ln.hako.vn/the-loai/historical", script: "gen.js"},
        {title: "Horror", input: "https://ln.hako.vn/the-loai/horror", script: "gen.js"},
        {title: "Incest", input: "https://ln.hako.vn/the-loai/incest", script: "gen.js"},
        {title: "Isekai", input: "https://ln.hako.vn/the-loai/isekai", script: "gen.js"},
        {title: "Josei", input: "https://ln.hako.vn/the-loai/josei", script: "gen.js"},
        {title: "Korean Novel", input: "https://ln.hako.vn/the-loai/korean-novel", script: "gen.js"},
        {title: "Magic", input: "https://ln.hako.vn/the-loai/magic", script: "gen.js"},
        {title: "Martial Arts", input: "https://ln.hako.vn/the-loai/martial-arts", script: "gen.js"},
        {title: "Mature", input: "https://ln.hako.vn/the-loai/mature", script: "gen.js"},
        {title: "Mecha", input: "https://ln.hako.vn/the-loai/mecha", script: "gen.js"},
        {title: "Military", input: "https://ln.hako.vn/the-loai/military", script: "gen.js"},
        {title: "Mystery", input: "https://ln.hako.vn/the-loai/mystery", script: "gen.js"},
        {title: "Netorare", input: "https://ln.hako.vn/the-loai/netorare", script: "gen.js"},
        {title: "One shot", input: "https://ln.hako.vn/the-loai/one-shot", script: "gen.js"},
        {title: "Otome Game", input: "https://ln.hako.vn/the-loai/otome-game", script: "gen.js"},
        {title: "Psychological", input: "https://ln.hako.vn/the-loai/psychological", script: "gen.js"},
        {title: "Reverse Harem", input: "https://ln.hako.vn/the-loai/reverse-harem", script: "gen.js"},
        {title: "Romance", input: "https://ln.hako.vn/the-loai/romance", script: "gen.js"},
        {title: "School Life", input: "https://ln.hako.vn/the-loai/school-life", script: "gen.js"},
        {title: "Science Fiction", input: "https://ln.hako.vn/the-loai/science-fiction", script: "gen.js"},
        {title: "Seinen", input: "https://ln.hako.vn/the-loai/seinen", script: "gen.js"},
        {title: "Shoujo", input: "https://ln.hako.vn/the-loai/shoujo", script: "gen.js"},
        {title: "Shoujo ai", input: "https://ln.hako.vn/the-loai/shoujo-ai", script: "gen.js"},
        {title: "Shounen", input: "https://ln.hako.vn/the-loai/shounen", script: "gen.js"},
        {title: "Shounen ai", input: "https://ln.hako.vn/the-loai/shounen-ai", script: "gen.js"},
        {title: "Slice of Life", input: "https://ln.hako.vn/the-loai/slice-of-life", script: "gen.js"},
        {title: "Sports", input: "https://ln.hako.vn/the-loai/sports", script: "gen.js"},
        {title: "Super Power", input: "https://ln.hako.vn/the-loai/super-power", script: "gen.js"},
        {title: "Supernatural", input: "https://ln.hako.vn/the-loai/supernatural", script: "gen.js"},
        {title: "Suspense", input: "https://ln.hako.vn/the-loai/suspense", script: "gen.js"},
        {title: "Tragedy", input: "https://ln.hako.vn/the-loai/tragedy", script: "gen.js"},
        {title: "Web Novel", input: "https://ln.hako.vn/the-loai/web-novel", script: "gen.js"},
        {title: "Yuri", input: "https://ln.hako.vn/the-loai/yuri", script: "gen.js"}
    ]);
}